version: 1.0.{build}

image: Visual Studio 2017

build_script:
- cmd: >-
    dotnet publish -r win-x86
    7z a reportportal-%VERSION%-win-x86.zip ./ReportPortal.Gauge/bin/Debug/netcoreapp2.1/win-x86/publish/*

artifacts:
- path: '**/.zip'