image: Visual Studio 2017 Preview

install:
  - ps: gitversion /l console /output buildserver

configuration: Release

environment:
  matrix:
    - runtime: win-x86
    - runtime: win-x64
    - runtime: linux-x64

dotnet_csproj:
  patch: true
  version: '$(GitVersion_SemVer)'

build_script:
- cmd: >-
    dotnet publish -c %configuration% -r %runtime%

    7z a reportportal-%GitVersion_SemVer%-%runtime%.zip ./ReportPortal.Gauge/bin/%configuration%/netcoreapp2.1/%runtime%/publish/*

artifacts:
  - path: '**/.zip'