version: 1.0.{build}

image: Visual Studio 2017

configuration: Release

environment:
  matrix:
    - runtime: win-x86
    - runtime: linux-x86

build_script:
- cmd: >-
    dotnet publish -c %configuration% -r %runtime%

    7z a reportportal-%APPVEYOR_BUILD_VERSION%-%runtime%.zip ./ReportPortal.Gauge/bin/%configuration%/netcoreapp2.1/%runtime%/publish/*
artifacts:
- path: '**/.zip'